### ISSUE TITLE
Arrumar overflow de tasks nos cards

### ISSUE THREAD

**Issue by RempelV** [l-eduardo/potential-pancake#51]
<img width="1495" alt="image" src="https://github.com/l-eduardo/potential-pancake/assets/74077303/8e3a4b73-20ca-47e6-9eaf-941876bde168">

Quando a task fica com descrição muito grande ela acaba aumentando o card como um todo e quebra o layout

**Comment by RempelV** [comment]
<img width="1508" alt="image" src="https://github.com/l-eduardo/potential-pancake/assets/74077303/50b8470a-0ef6-4f3a-a7e2-15995412fb44">

É pra ficar assim

**Comment by l-eduardo** [comment]
Muito top
